export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAIL = "ADD_PRODUCT_FAIL";

export const FETCH_PRODUCTSPAGE_START = "FETCH_PRODUCTSPAGE_START";
export const FETCH_PRODUCTSPAGE_SUCCESS = "FETCH_PRODUCTSPAGE_SUCCESS";
export const FETCH_PRODUCTSPAGE_FAIL = "FETCH_PRODUCTSPAGE_FAIL";

export const CHANGE_PAGE_NO = "CHANGE_PAGE_NO";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
