export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAIL = "ADD_PRODUCT_FAIL";

export const FETCH_PRODUCTSPAGE_START = "FETCH_PRODUCTSPAGE_START";
export const FETCH_PRODUCTSPAGE_SUCCESS = "FETCH_PRODUCTSPAGE_SUCCESS";
export const FETCH_PRODUCTSPAGE_FAIL = "FETCH_PRODUCTSPAGE_FAIL";

export const CHANGE_PAGE_NO = "CHANGE_PAGE_NO";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";

export const INCREASE_PRODUCT = "INCREASE_PRODUCT";
export const DECREASE_PRODUCT = "DECREASE_PRODUCT";

export const MAKE_PAYMENT_START = "MAKE_PAYMENT_START";
export const MAKE_PAYMENT_SUCCESS = "MAKE_PAYMENT_SUCCESS";
export const MAKE_PAYMENT_FAIL = "MAKE_PAYMENT_FAIL";

export const REGISTER_USER_START = "REGISTER_USER_START";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";

export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const CLEAR_ERROR = "CLEAR_ERROR";

export const LOGOUT = "LOGOUT";

export const FETCH_ORDER_HISTORY_START = "FETCH_ORDER_HISTORY_START";
export const FETCH_ORDER_HISTORY_SUCCESS = "FETCH_ORDER_HISTORY_SUCCESS";
export const FETCH_ORDER_HISTORY_FAIL = "FETCH_ORDER_HISTORY_FAIL";
